# Generated by Django 3.0.2 on 2020-05-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0006_auto_20200512_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default=True, max_length=128),
        ),
    ]
