# Generated by Django 3.0.2 on 2020-05-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0007_project_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mypic', models.ImageField(upload_to='images/')),
                ('summary', models.CharField(max_length=512)),
            ],
        ),
    ]
