# Generated by Django 3.0.2 on 2020-05-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0008_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='summary',
            field=models.TextField(max_length=512),
        ),
    ]
